#file: noinspection undefined
---

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
  output:
    ansi:
      enabled: always
  profiles:
    default: development
  application:
    name: app
  h2:
    console:
      enabled: true

server:
  address: 0.0.0.0
  port: 8080

  springdoc:
    swagger-ui: swagger-ui.html

sentry:
  dns: https://fa2044e194047c3fafe4db9748c646b9@o4507881789849600.ingest.de.sentry.io/4507881805185104
  traces-sample-rate: 1.0

logging:
  level:
    org:
      springframework:
        security=trace:
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem


